import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import ClientSideScrollRestorer from "../useScrollRestorer";
import { AuthProvider } from "../context/AuthProvider";
import Footer from "../components/layout/Footer";
import Navbar from "../components/layout/Navbar";
import { getCookieServer } from "../lib/getToken";
import { Theme }  from '@radix-ui/themes';
import { Toaster } from "sonner";
import QueryProvider from "../components/providers/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const token = await getCookieServer('token');

  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <QueryProvider>
          <AuthProvider>
            <Theme>
              {token ? <Navbar /> : null}
              {children}
              {token ? <Footer /> : null}
              <Toaster />
            </Theme>
          </AuthProvider>
        </QueryProvider>
        <Suspense>
          <ClientSideScrollRestorer/>
        </Suspense>
      </body>
    </html>
  );
}
